[build]
  command = "rm -rf .netlify build node_modules/.vite && npm install --frozen-lockfile --prefer-offline && npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# =====================================================
# 🔒 BULLETPROOF FINTECH SECURITY HEADERS
# =====================================================

# GLOBAL SECURITY (MAXIMUM PROTECTION)
[[headers]]
  for = "/*"
  [headers.values]
    # FinTech Security Identity
    X-FinTech-Security = "bulletproof"
    X-Payment-Security = "PCI-DSS-ready"
    X-Security-Version = "2025-07-13-final"
    
    # Core Security Headers
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HSTS (MAXIMUM + PRELOAD)
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # CSP (BULLETPROOF - FINTECH GRADE)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://js.stripe.com https://checkout.paypal.com https://www.paypal.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://logos.stripe.com https://www.paypalobjects.com https://images.coinbase.com; connect-src 'self' https://api.stripe.com https://api.paypal.com https://api.coinbase.com https://minumiricmuddzcyxyzd.supabase.com https://*.supabase.co wss://*.supabase.co; object-src 'none'; base-uri 'self'; form-action 'self' https://api.stripe.com https://www.paypal.com; frame-ancestors 'none'; upgrade-insecure-requests;"
    
    # Advanced Security Headers
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# PAYMENT API SECURITY (ULTRA-STRICT)
[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    X-API-Type = "payment-critical"
    X-PCI-Compliance = "required"
    cache-control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Access-Control-Allow-Origin = "https://theblockchain.ai"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "300"

# WEBHOOK SECURITY (SIGNATURE VALIDATION)
[[headers]]
  for = "/api/webhooks/*"
  [headers.values]
    X-Webhook-Security = "signature-required"
    cache-control = "no-store, no-cache, must-revalidate, private"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"

# ADMIN ENDPOINTS (LOCKDOWN)
[[headers]]
  for = "/api/admin/*"
  [headers.values]
    X-Admin-Security = "maximum"
    cache-control = "no-store, no-cache, must-revalidate, private"
    X-Robots-Tag = "noindex, nofollow, noarchive"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"

# STATIC ASSETS (SECURE CACHING)
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# =====================================================
# 🔐 ENVIRONMENT SECURITY
# =====================================================

[context.production.environment]
  NODE_ENV = "production"
  SECURITY_MODE = "bulletproof"

[context.deploy-preview.environment]
  NODE_ENV = "staging" 
  SECURITY_MODE = "high"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  SECURITY_MODE = "development"