[build]
  # SvelteKit build command with security validation
  command = "rm -rf .netlify build node_modules/.vite && npm ci && npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Security-first deployment
  NETLIFY_SKIP_EDGE_FUNCTIONS_CACHE = "true"
  NETLIFY_SKIP_BUILD_CACHE = "true"

# =====================================================
# 🔒 BULLETPROOF FINTECH SECURITY HEADERS
# =====================================================

# GLOBAL SECURITY (STRICTEST POSSIBLE)
[[headers]]
  for = "/*"
  [headers.values]
    # FinTech Identity
    X-FinTech-Security = "enabled"
    X-Payment-Security = "PCI-DSS-Level-1"
    X-Deployment-Version = "bulletproof-2025-07-13"
    
    # XSS Protection (STRICT)
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    
    # Referrer Policy (STRICT)
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HSTS (MAXIMUM SECURITY + PRELOAD)
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # CSP (BULLETPROOF - NO UNSAFE DIRECTIVES)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://js.stripe.com https://checkout.paypal.com; style-src 'self' 'sha256-SPECIFIC-HASH' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://logos.stripe.com https://www.paypalobjects.com https://images.coinbase.com; connect-src 'self' https://api.stripe.com https://api.paypal.com https://api.coinbase.com https://minumiricmuddzcyxyzd.supabase.com; object-src 'none'; base-uri 'self'; form-action 'self' https://api.stripe.com; frame-ancestors 'none';"
    
    # Additional FinTech Headers
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# PAYMENT API ENDPOINTS (MAXIMUM SECURITY)
[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    # Stripe-Specific Security
    X-API-Type = "payment-processing"
    X-PCI-Compliance = "required"
    X-Rate-Limit-Warning = "enabled"
    
    # No Caching (SECURITY)
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"
    
    # CORS (STRICT)
    Access-Control-Allow-Origin = "https://theblockchain.ai"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Stripe-Signature, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "300"
    
    # Security Headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin"

# WEBHOOK ENDPOINTS (ULTRA-SECURE)
[[headers]]
  for = "/api/*/webhooks/*"
  [headers.values]
    # Webhook Security
    X-Webhook-Security = "signature-required"
    X-Signature-Validation = "mandatory"
    
    # No Caching
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    
    # Strict CORS
    Access-Control-Allow-Origin = "null"
    
    # Security
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# ADMIN ENDPOINTS (LOCKDOWN)
[[headers]]
  for = "/api/admin/*"
  [headers.values]
    # Admin Security
    X-Admin-Access = "restricted"
    X-Auth-Required = "true"
    
    # No Caching
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    
    # Hide from Search Engines
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
    
    # Strict Security
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"

# STATIC ASSETS (OPTIMIZED BUT SECURE)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# SECURITY ENDPOINTS (SPECIAL)
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Security-Config = "enabled"

# =====================================================
# 🛡️ ENVIRONMENT CONTEXTS (SECURE)
# =====================================================

[context.production.environment]
  NODE_ENV = "production"
  SECURITY_MODE = "maximum"
  NETLIFY_SKIP_EDGE_FUNCTIONS_CACHE = "true"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  SECURITY_MODE = "high"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  SECURITY_MODE = "development"