[build]
  # SvelteKit build command with aggressive cache busting
  command = "rm -rf .netlify build node_modules/.vite && npm ci && npm run build"
  publish = "build"
  # Clear all caches
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 
  # Force fresh deployment v3
  NETLIFY_SKIP_EDGE_FUNCTIONS_CACHE = "true"
  NETLIFY_SKIP_BUILD_CACHE = "true"

# =====================================================
# 🔒 SECURITY HEADERS (v2 - DEPLOYMENT FORCED)
# =====================================================

# Global security headers (updated for deployment)
[[headers]]
  for = "/*"
  [headers.values]
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    
    # Deployment verification v3
    X-Deployment-Version = "v3-supabase-fix-2025-07-13"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (FIXED v3 - Explicit Supabase domains)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.anthropic.com https://generativelanguage.googleapis.com https://js.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.anthropic.com https://generativelanguage.googleapis.com https://minumiricmuddzcyxyzd.supabase.com https://*.supabase.co https://*.supabase.com wss://*.supabase.co wss://*.supabase.com https://api.stripe.com https://fonts.googleapis.com https://api.paypal.com https://www.paypal.com https://*.coinbase.com; object-src 'none'; base-uri 'self';"
    
    # HSTS (HTTPS Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# API-specific headers (enhanced)
[[headers]]
  for = "/api/*"
  [headers.values]
    # Deployment verification
    X-API-Version = "v2-split-functions"
    
    # CORS headers (will be overridden by dynamic CORS in code)
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"
    
    # Additional security
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "no-store, no-cache, must-revalidate"

# Search API performance headers
[[headers]]
  for = "/api/search"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"
    X-Function-Type = "split-endpoint"

# Suggestions API caching
[[headers]]
  for = "/api/suggestions"
  [headers.values]
    Cache-Control = "public, max-age=600, s-maxage=600"

# Admin endpoints - extra security
[[headers]]
  for = "/api/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Robots-Tag = "noindex, nofollow"

# Static assets optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# =====================================================
# REDIRECTS & FUNCTIONS (v3)
# =====================================================

# API function routing - remove force to let SvelteKit handle
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# Specific stripe routing 
[[redirects]]
  from = "/api/stripe/*"
  to = "/.netlify/functions/stripe-:splat"
  status = 200

# =====================================================
# ENVIRONMENT CONTEXT
# =====================================================

[context.production.environment]
  # Production environment
  NETLIFY_SKIP_EDGE_FUNCTIONS_CACHE = "true"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"