[build]
  # Install dependencies for both main app and functions
  command = "npm install && cd netlify/functions && npm install && cd ../.. && npm run build"
  publish = "build"
  # Tell Netlify where functions are located
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# =====================================================
# 🔒 SECURITY HEADERS
# =====================================================

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (adjust as needed)
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.anthropic.com https://generativelanguage.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://api.anthropic.com https://generativelanguage.googleapis.com https://*.supabase.co wss://*.supabase.co;
      object-src 'none';
      base-uri 'self';
    '''
    
    # HSTS (HTTPS Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# API-specific headers
[[headers]]
  for = "/api/*"
  [headers.values]
    # CORS headers (will be overridden by dynamic CORS in code)
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"
    
    # Additional security
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "no-store, no-cache, must-revalidate"

# Search API performance headers
[[headers]]
  for = "/api/search"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"

# Suggestions API caching
[[headers]]
  for = "/api/suggestions"
  [headers.values]
    Cache-Control = "public, max-age=600, s-maxage=600"

# Admin endpoints - extra security
[[headers]]
  for = "/api/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    X-Robots-Tag = "noindex, nofollow"

# Static assets optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# =====================================================
# 🔄 REDIRECTS
# =====================================================

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =====================================================
# ENVIRONMENT CONTEXT
# =====================================================

[context.production.environment]
  # Production environment

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
